version: "3"
services:
  tech-challenge-db:
    image: postgres:16.3
    container_name: "TechChallenge_DB_Postgres"
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "./data:/var/lib/postgresql/data"
      #- ./sql/sql-initial.sql:/docker-entrypoint-initdb.d/db.sql:ro
      #- "/etc/timezone:/etc/timezone:ro"
      #- "/etc/localtime:/etc/localtime:ro"
    networks:
      - tech-challenge-network
    ports:
      - 5432:5432

  tech-challenge-api:
    image: felipetomm/fiap-soat-7:tech-challenge-api
    container_name: "TechChallenge_WebAPI"
    restart: unless-stopped
    depends_on:
      - tech-challenge-db
    networks:
      - tech-challenge-network
    environment:
      - DB_CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};Search Path=${DB_NAME};
    ports:
      - 8080:8080

networks:
  tech-challenge-network:
    driver: bridge
