apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  connectionString: U2VydmVyPXN2Yy10ZWNoLWNoYWxsZW5nZS1kYjtEYXRhYmFzZT1idXJndWVyZGI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM7U2VhcmNoIFBhdGg9YnVyZ3VlcmRiOw==
  dbUserName: cG9zdGdyZXM=
  dbUserPass: cG9zdGdyZXM=
  dbDatabaseName: YnVyZ3VlcmRi
