apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database-postgres
  labels:
    name: pvc-database-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
