apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tech-challenge-api
  name: svc-tech-challenge-api
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    io.kompose.service: tech-challenge-api
