apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tech-challenge-db
  name: dpl-tech-challenge-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tech-challenge-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tech-challenge-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: dbDatabaseName
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: dbUserPass
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: dbUserName
          image: postgres:16.3
          name: tech-challenge-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-database-postgres
      restartPolicy: Always
