apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: tech-challenge-db
  name: svc-tech-challenge-db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30002
  selector:
    io.kompose.service: tech-challenge-db
