apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: tech-challenge-db
  name: svc-tech-challenge-db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30002
  selector:
    io.kompose.service: tech-challenge-db
