apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: tech-challenge-api
  name: dpl-tech-challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tech-challenge-api
  template:
    metadata:
      labels:
        io.kompose.service: tech-challenge-api
    spec:
      containers:
        - image: felipetomm/fiap-soat-7:tech-challenge-api
          name: tech-challenge-api
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: connectionString
      restartPolicy: Always
