apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: tech-challenge-db
  name: tech-challenge-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tech-challenge-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: tech-challenge-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: burguerdb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:16.3
          name: tech-challenge-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
