apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: tech-challenge-api
  name: dpl-tech-challenge-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tech-challenge-api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: tech-challenge-api
    spec:
      containers:
        - image: felipetomm/fiap-soat-7:tech-challenge-api
          name: tech-challenge-api
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
